### ISSUE TITLE
Proposal: tag version 0.1.0 ?

### ISSUE THREAD

**Issue by npillmayer** [flopp/go-findfont#11]
Hi,

firstly, thank your for investing your time in a general purpose library !

As your lib seems to be quite stable over the last couple of month, would you mind tagging it with a zero version; something like `v0.1.0`?  A zero version would not mean any commitment to API-stability from your side, as zero versions are supposed to be unstable.

However, it would help clients lock their dependencies in case you'll extend your lib to include `fc-match` or other feature-/API-changes.

Cheers,
--Norbert

**Comment by flopp** [comment]
Done.

Thank you for the proposal!
