### ISSUE TITLE
go get fails on Windows and Mac

### ISSUE THREAD

**Issue by JoshVarga** [flopp/go-findfont#2]
The platform specific files do not support "unix" as an option, so condition build tags need to be added to  fontdirs-unix.go

I have included a pull request #3

**Comment by flopp** [comment]
Thanks for the bug report. I actually didn't try to "go get" the library on non-linux systems :(

**Comment by JoshVarga** [comment]
I have a need for my code to run on nearly any platform and I do hop between Linux, Windows and Mac. Glad this helped.
